### PR TITLE
updated API routines.

### LINKED ISSUE #1: HTTP 401 when opening live stream
Thanks a lot for this plugin! While it does not work (yet), I trust it will get into a working state soon.
```
2020-10-25 18:49:44.638 T:3467665632   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 92: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mindigo/default.py", line 297, in <module>
                                                params.get("icon"),
                                              File "/home/osmc/.kodi/addons/plugin.video.mindigo/default.py", line 234, in translate_link
                                                % (response.status_code, response.content.encode("utf-8"))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 92: ordinal not in range(128)
                                            -->End of Python script error report<--
```

and a second one, loosely related:
```
2020-10-25 18:49:37.227 T:3459272928   ERROR: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for https://static.mindigo.hu/channels/hetitv.png
2020-10-25 18:49:39.556 T:3476058336   ERROR: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for https://static.mindigo.hu/channels/hirtv.png

```

### PR DESCRIPTION
**Pull request by ratcashdev**
fixes #1 
In addition, uses provided fan-art and descriptions

### CODE REVIEW

**Comment by MrDini123** [comment]
Hi,

Sorry that it took me so long until I got to the point to further review this.

Overall it looks very well and logically implemented, thank you so much for the PR. However there are some parts where you used upper-case variable namings, which is by design not so PEP8 friendly.

Also, is there any particular reason why you decided to use inputstream to play mpeg-dash streams? Kodi can just play it fine by itself and then it is one less dependency + the platforms before Leia are supported as well. inputstream is usually only required for DRM protected content where you have a license request involved.

Lastly, I am not sure if it is efficient to store a requests.Session object in a setting value. And I would prefer to send the individual requests using the method found in my utils lib or in a similar way without involving the initialization of a whole session object which is on the other hand useless even as it gets lost at every script call...

Though I like the idea that you separated the client to its own module, it indeed makes the debugging a lot easier.

And one last thought... Upon testing, I couldn't get the login to work as it said the server responded with a 302. These are the important lines:

https://github.com/ratcashdev/MindiGo/blob/master/plugin.video.mindigo/default.py#L74-L79

Let me know if you can fix those mentioned above or I could try to give it a try myself.

**Comment by ratcashdev** [comment]
* PEP8: apologies for that. This is (probably) my second python project, so naming conventions are yet unknown to me.
* InputStream: I copied something I found on the web as an example to tell kodi to play DASH. If you can show me how to do it natively in KODI I am all for it. The lower the number of deps the better.
* session object: I am not sure if I store the session object, merely the value of the sessionId cookie (AFAIK).
* utils lib: going by the path of least resistance I had to copy/duplicate methods I needed to quickly test the client in the console because the KODI dependencies in the UTILs lib made my life a lot harder. If you perhaps split utils into 2 classes (one which only deals with stuff not requiring KODI, and the other for KODI helpers methods) that would help and maybe also beneficial when using something like `tox`.
* HTTP 302: no idea why you'd be getting that. When doing the login through 
```
curl 'https://mindigtvgo.hu/sb/login?deviceType=WEB&tenantId=1' \                                         
  -H 'Accept: application/json' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Origin: https://mindigtvgo.hu' \
  -H 'Referer: https://mindigtvgo.hu/home' \
  -H 'Accept-Language: en-US,en;q=0.9,hu;q=0.8,sk;q=0.7,de;q=0.6' \
  -H 'Cookie: __gfp_64b=-TURNEDOFF' \
  --data-raw $'username=asd@email.com&password=pw123' \        
  --compressed
```
I am not getting any HTTP 302 response

**Comment by MrDini123** [comment]
Regarding Inputstream, you can simply call the play method of my routines:
```py
    routines.play(
        int(sys.argv[1]),
        mpd_direct_url,
        "video",
        user_agent=utils.get_setting("user_agent"),
        name=name,
        icon=icon,
    )
```

If the certain content is not DRM protected, Kodi should play it just fine. 

I figured the issue around the 302 too as in your example you are using the new pathes already while in the code the pathes are still pointing to the old API and therefore I am getting a 302 redirect. I believe we should change them to that:

```py
	API_BASE = "470098bXNyZXBvIGh0dHBzOi8vbWluZGlndHZnby5odS9zYi8="
	MAIN_URI = "470098bXNyZXBvIGh0dHBzOi8vbWluZGlndHZnby5odQ=="
```

After that it started to work for me too.

However going further to click on the live channel list I got the following error in the console:

```
2020-11-06 14:28:21.604 T:6020   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'int' object is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\MrDini\AppData\Roaming\Kodi\addons\plugin.video.mindigo\default.py", line 209, in <module>
                                                live_window()
                                              File "C:\Users\MrDini\AppData\Roaming\Kodi\addons\plugin.video.mindigo\default.py", line 129, in live_window
                                                channelsList = ",".join([str(k) for k,v in allChannels])
                                            TypeError: 'int' object is not iterable
                                            -->End of Python script error report<--
```

A quick fix, such as `channelsList = ",".join(map(str, allChannels.keys()))` fixed the issue though.

Then the next error I got:
```
2020-11-06 14:40:07.294 T:5264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: MindigoClient instance has no attribute 'base_url'
                                            Traceback (most recent call last):
                                              File "C:\Users\MrDini\AppData\Roaming\Kodi\addons\plugin.video.mindigo\default.py", line 210, in <module>
                                                live_window()
                                              File "C:\Users\MrDini\AppData\Roaming\Kodi\addons\plugin.video.mindigo\default.py", line 153, in live_window
                                                icon="%s%s" % (client.base_url, program["imageUrls"]["channel_logo"]),
                                            AttributeError: MindigoClient instance has no attribute 'base_url'
                                            -->End of Python script error report<--
```

Seems like a typo here to me, changing it to `icon="%s%s" % (client.web_url, program["imageUrls"]["channel_logo"]),` did the trick for me.

So far so good. With these changes I managed to get all the functionality working just fine.

And my apologies for the requests.Session comment, the fact that you called your variable storing the token `session` made me confused, but I took a deeper look in the code and it seems to be fine.

And regarding the separation of platform dependent/independent modules, this could be done actually, but I got no idea how it would be optimal. Probably for that I would need to submit the package to pip for easier obtaining. I personally just test my code in place at the kodi addons folder which is on Windows `%APPDATA%\Kodi\addons\plugin.video.mindigo\default.py` and simply keep kodi open to test my changes after each save which is indeed a dirty way, but it works just fine. ☺️

**Comment by ratcashdev** [comment]
That is all strange. The whole plugin works on my end (using it daily) with the `API_BASE` and `MAIN_URI` as submitted.
I think what I might have done is a lousy job on moving all the changes from my KODI box (ARM Linux) back to my laptop for git commit.

Edit: Indeed the case, please check the latest commit - this does not include the improvement you suggested, but at least should make it working. If it does, then we can move on fixing the conceptual stuff.

**Comment by ratcashdev** [comment]
Started getting HTTP 302 too. Using `470098bXNyZXBvIGh0dHBzOi8vbWluZGlndHZnby5odS9zYi8=` as API_BASE solves it indeed. They have indeed changed the URI since I have submitted this PR.

**Comment by ratcashdev** [comment]
I have tried using the native play as suggested, but it resulted in error as follows (anonymized):
```
2020-11-09 18:17:00.617 T:4072534032  NOTICE: VideoPlayer::OpenFile: https://server.com/61102/uuid/shortid/manifest.mpd?v=5sip:ip.address.of.server|User-Agent=selected_user_agent
2020-11-09 18:17:00.634 T:3242184928  NOTICE: Creating InputStream
2020-11-09 18:17:00.861 T:3242184928  NOTICE: Creating Demuxer
2020-11-09 18:17:00.872 T:3242184928   ERROR: Open - error probing input format, https:/server.com/61102/uuid/shortid/manifest.mpd?v=5sip:ip.address.of.server
2020-11-09 18:17:00.872 T:3242184928   ERROR: OpenDemuxStream - Error creating demuxer
2020-11-09 18:17:00.872 T:3242184928  NOTICE: CVideoPlayer::OnExit()
2020-11-09 18:17:00.895 T:4072534032  NOTICE: CVideoPlayer::CloseFile()
```
The rest of the findings should be fixed, hopefully.

**Pull request merged**
