### PR TITLE
API Update, bugfixes and integration with EPG

### PR DESCRIPTION
**Pull request by ratcashdev**
opposed to local time as that may return only outdated epg.

### CODE REVIEW

**Comment by Diniboy1123** [comment]
The problem with the current implementation is that a channel listing depends on the epg. If there is no epg it's not even added to the list. Since the epg is something extra but something not even necessary to have I was thinking about adding the channels based on their names to the list and of course attach the epg if it's available. But I haven't found a way so far to resolve the links without relying on the epg endpoint so I am not sure where to take the project.

However the timezone change seems to be necessary indeed.

PS: @MrDini123 is quite busy nowadays. ☺️

**Comment by ratcashdev** [comment]
@Diniboy1123  Not sure if I follow. Based on the code, first the channel list is retrieved. That is afterwards filtered for channels that are playable (opposed to being `PREVIEW` only). The list of playable channels are then fed to the epg method to get the epg of only the relevant channels.

EDIT: It has to be that way (if there's no EPG, no channel is available) since we can only ask to play a specific EPG entry, not a channel as such.

**Comment by ratcashdev** [comment]
@Diniboy1123 Just a heads up, I have significantly enhanced this plugin.
* fixed known issues (favorites)
* made it work with encrypted content
* added support to be integrated with Simple IPTV PVR*

**Comment by ratcashdev** [comment]
@MrDini123  please have a look on this PR. Thanks.

**Comment by Thomassso** [comment]
I'm asking very kindly to confirm the latest pull request and make a realase! I'm waiting patiently.

**Comment by Thomassso** [comment]
@Diniboy1123 , @MrDini123 : Please assign developer rights to ratcashdev in order to keep this project live. I will try to help too.

**Comment by MrDini123** [comment]
Pushed it, latest release is available within the repository.

**Pull request merged**
